version: '3'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    volumes:
      - ./server/nginx/cert:/etc/nginx/conf.d
      - ./server/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/html:/usr/share/nginx/wwwroot

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${redisPwd}
    ports: 
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./server/mysql/data:/var/lib/mysql
      - ./server/mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${mysqlPwd}
      - TZ=Asia/Shanghai