version: '3'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${redisPwd}
    ports: 
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/mac/Projects/web/node-tutorial/mysql/data:/var/lib/mysql
      - /Users/mac/Projects/web/node-tutorial/mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${mysqlPwd}
      - TZ=Asia/Shanghai
